export const ADD_CARD = 'ADD_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const DELETE_CARD_MANY = 'DELETE_CARD_MANY';
export const ADDRESS_UPDATE = 'ADDRESS_UPDATE';
export const LATLANG_UPDATE = 'LATLANG_UPDATE';
